sonar.organization=rettichschnidi
sonar.projectKey=rettichschnidi_wakaama
sonar.exclusions=sonar-cloud-build-wrapper-output/**, build-wakaama-*/**, .git/**
sonar.host.url=https://sonarcloud.io
sonar.cfamily.cache.enabled=false
# As of 2020-02-29, the CI machines have two cores
sonar.cfamily.threads=2

# relative paths to source directories. More details and properties are described
# in https://sonarcloud.io/documentation/project-administration/narrowing-the-focus/
sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.cfamily.build-wrapper-output=build-wakaama-tests/sonar-cloud-build-wrapper-output

