name: Compilation only checks

on: [push, pull_request]

jobs:
  standards:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        compiler: ["clang-14", "gcc-12"]
        c_standard: ["99", "11"]
        c_extensions: ["ON", "OFF"]

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run: |
        sudo apt-get update
        sudo apt-get install libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build all binaries
      run: |
        tools/ci/run_ci.sh \
          --run-build \
          --c-standard ${{ matrix.c_standard }} \
          --c-extensions ${{ matrix.c_extensions }}
      env:
        CC:  ${{ matrix.compiler }}

  standalone-examples:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        example: ["bootstrap_server", "client", "lightclient", "server"]

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run: |
        sudo apt-get update
        sudo apt-get install libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build examples as stand-alone projects
      run: |
        tools/ci/run_ci.sh \
          --run-clean \
          --run-build \
          --source-directory examples/${{ matrix.example }}
