name: Compliance

on: pull_request

jobs:
  lint-code:
    name: Run compliance checks
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code including full history
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Install compliance tools
      run: |
        sudo apt update
        sudo apt -qy --no-install-recommends install clang-format-10
        pip3 install gitlint

    - name: Check commits with gitlint
      run: |
        tools/ci/run_ci.sh --branch-target origin/${{ github.base_ref }} --run-gitlint

    - name: Check C code (delta) with clang-format
      run: |
        tools/ci/run_ci.sh --branch-target origin/${{ github.base_ref }} --run-clang-format

    - name: Check Python code with pylint
      run: |
          cd tests
          pylint integration
