name: Measure coverage

on: [push, pull_request]

jobs:
  coverage:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run: sudo apt-get install gcovr libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Collect test coverage data
      run: |
        tools/ci/run_ci.sh --run-tests \
          --clean \
          --test-coverage html

    - name: Upload HTML coverage report
      uses: actions/upload-artifact@v1
      with:
        name: Coverage Report (HTML)
        path: build-wakaama-tests/coverage

    - uses: mszlgr/lcov-reporter-action@v0.2.23
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        lcov-file: build-wakaama-tests/coverage/lcov.info
