name: Build and Test

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build_and_test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        sanitizer: ["address", "leak", "thread", "undefined"]

    steps:
    - name: Checkout code including full history and submodules
      uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0

    - name: Install dependencies from APT repository
      run: sudo apt-get install libcunit1-dev wget unzip

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Install Ninja
      uses: seanmiddleditch/gha-setup-ninja@master

    - name: Build all binaries
      run: |
        tools/ci/run_ci.sh --build --verbose

    - name: Build, execute sanititzed unit tests
      run: |
        tools/ci/run_ci.sh --run-tests --clean --sanitizer ${{ matrix.sanitizer }}
